name: SpellCheck
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: SpellCheck
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pyspelling
      - name: run pyspelling
        run: pyspelling -c spellcheck.yaml
